provider: aws
domainFilters:
  - yourdomain.com
txtOwnerId: eks-production-cluster
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::314323855520:role/eks-production-cluster-external-dns"
policy: sync
