apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frontend.fullname" . }}-ingress
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- if .Values.domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ printf "app.%s" .Values.domain }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- if .Values.domain }}
    - host: {{ printf "app.%s" .Values.domain }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
