{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "frontend.fullname" . }}-deployment-vpa
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "frontend.fullname" . }}-deployment
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode | default "Off" | quote }}
{{- end }}
